package com.wcq.thang.model;

import java.util.Date;

public class Mature {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mature.mature_id
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    private Integer matureId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mature.tags
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    private String tags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mature.source
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mature.uploader
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    private Integer uploader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mature.date
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mature.content
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mature.mature_id
     *
     * @return the value of mature.mature_id
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    public Integer getMatureId() {
        return matureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mature.mature_id
     *
     * @param matureId the value for mature.mature_id
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    public void setMatureId(Integer matureId) {
        this.matureId = matureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mature.tags
     *
     * @return the value of mature.tags
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mature.tags
     *
     * @param tags the value for mature.tags
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mature.source
     *
     * @return the value of mature.source
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mature.source
     *
     * @param source the value for mature.source
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mature.uploader
     *
     * @return the value of mature.uploader
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    public Integer getUploader() {
        return uploader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mature.uploader
     *
     * @param uploader the value for mature.uploader
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    public void setUploader(Integer uploader) {
        this.uploader = uploader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mature.date
     *
     * @return the value of mature.date
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mature.date
     *
     * @param date the value for mature.date
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mature.content
     *
     * @return the value of mature.content
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mature.content
     *
     * @param content the value for mature.content
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}