package com.wcq.thang.model;

import java.util.Date;

public class Original {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column original.original_id
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    private Integer originalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column original.title
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column original.url
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column original.uploader
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    private Integer uploader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column original.date
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column original.source
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column original.original_format
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    private String originalFormat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column original.format_changed
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    private Boolean formatChanged;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column original.txt_path
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    private String txtPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column original.cleaned
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    private Boolean cleaned;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column original.cleaned_path
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    private String cleanedPath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column original.original_id
     *
     * @return the value of original.original_id
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    public Integer getOriginalId() {
        return originalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column original.original_id
     *
     * @param originalId the value for original.original_id
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    public void setOriginalId(Integer originalId) {
        this.originalId = originalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column original.title
     *
     * @return the value of original.title
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column original.title
     *
     * @param title the value for original.title
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column original.url
     *
     * @return the value of original.url
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column original.url
     *
     * @param url the value for original.url
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column original.uploader
     *
     * @return the value of original.uploader
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    public Integer getUploader() {
        return uploader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column original.uploader
     *
     * @param uploader the value for original.uploader
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    public void setUploader(Integer uploader) {
        this.uploader = uploader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column original.date
     *
     * @return the value of original.date
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column original.date
     *
     * @param date the value for original.date
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column original.source
     *
     * @return the value of original.source
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column original.source
     *
     * @param source the value for original.source
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column original.original_format
     *
     * @return the value of original.original_format
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    public String getOriginalFormat() {
        return originalFormat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column original.original_format
     *
     * @param originalFormat the value for original.original_format
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    public void setOriginalFormat(String originalFormat) {
        this.originalFormat = originalFormat == null ? null : originalFormat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column original.format_changed
     *
     * @return the value of original.format_changed
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    public Boolean getFormatChanged() {
        return formatChanged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column original.format_changed
     *
     * @param formatChanged the value for original.format_changed
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    public void setFormatChanged(Boolean formatChanged) {
        this.formatChanged = formatChanged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column original.txt_path
     *
     * @return the value of original.txt_path
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    public String getTxtPath() {
        return txtPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column original.txt_path
     *
     * @param txtPath the value for original.txt_path
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    public void setTxtPath(String txtPath) {
        this.txtPath = txtPath == null ? null : txtPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column original.cleaned
     *
     * @return the value of original.cleaned
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    public Boolean getCleaned() {
        return cleaned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column original.cleaned
     *
     * @param cleaned the value for original.cleaned
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    public void setCleaned(Boolean cleaned) {
        this.cleaned = cleaned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column original.cleaned_path
     *
     * @return the value of original.cleaned_path
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    public String getCleanedPath() {
        return cleanedPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column original.cleaned_path
     *
     * @param cleanedPath the value for original.cleaned_path
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    public void setCleanedPath(String cleanedPath) {
        this.cleanedPath = cleanedPath == null ? null : cleanedPath.trim();
    }
}