package com.wcq.thang.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class OriginalExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table original
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table original
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table original
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table original
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    public OriginalExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table original
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table original
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table original
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table original
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table original
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table original
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table original
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table original
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table original
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table original
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table original
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andOriginalIdIsNull() {
            addCriterion("original_id is null");
            return (Criteria) this;
        }

        public Criteria andOriginalIdIsNotNull() {
            addCriterion("original_id is not null");
            return (Criteria) this;
        }

        public Criteria andOriginalIdEqualTo(Integer value) {
            addCriterion("original_id =", value, "originalId");
            return (Criteria) this;
        }

        public Criteria andOriginalIdNotEqualTo(Integer value) {
            addCriterion("original_id <>", value, "originalId");
            return (Criteria) this;
        }

        public Criteria andOriginalIdGreaterThan(Integer value) {
            addCriterion("original_id >", value, "originalId");
            return (Criteria) this;
        }

        public Criteria andOriginalIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("original_id >=", value, "originalId");
            return (Criteria) this;
        }

        public Criteria andOriginalIdLessThan(Integer value) {
            addCriterion("original_id <", value, "originalId");
            return (Criteria) this;
        }

        public Criteria andOriginalIdLessThanOrEqualTo(Integer value) {
            addCriterion("original_id <=", value, "originalId");
            return (Criteria) this;
        }

        public Criteria andOriginalIdIn(List<Integer> values) {
            addCriterion("original_id in", values, "originalId");
            return (Criteria) this;
        }

        public Criteria andOriginalIdNotIn(List<Integer> values) {
            addCriterion("original_id not in", values, "originalId");
            return (Criteria) this;
        }

        public Criteria andOriginalIdBetween(Integer value1, Integer value2) {
            addCriterion("original_id between", value1, value2, "originalId");
            return (Criteria) this;
        }

        public Criteria andOriginalIdNotBetween(Integer value1, Integer value2) {
            addCriterion("original_id not between", value1, value2, "originalId");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andUrlIsNull() {
            addCriterion("url is null");
            return (Criteria) this;
        }

        public Criteria andUrlIsNotNull() {
            addCriterion("url is not null");
            return (Criteria) this;
        }

        public Criteria andUrlEqualTo(String value) {
            addCriterion("url =", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotEqualTo(String value) {
            addCriterion("url <>", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThan(String value) {
            addCriterion("url >", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThanOrEqualTo(String value) {
            addCriterion("url >=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThan(String value) {
            addCriterion("url <", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThanOrEqualTo(String value) {
            addCriterion("url <=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLike(String value) {
            addCriterion("url like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotLike(String value) {
            addCriterion("url not like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlIn(List<String> values) {
            addCriterion("url in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotIn(List<String> values) {
            addCriterion("url not in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlBetween(String value1, String value2) {
            addCriterion("url between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotBetween(String value1, String value2) {
            addCriterion("url not between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUploaderIsNull() {
            addCriterion("uploader is null");
            return (Criteria) this;
        }

        public Criteria andUploaderIsNotNull() {
            addCriterion("uploader is not null");
            return (Criteria) this;
        }

        public Criteria andUploaderEqualTo(Integer value) {
            addCriterion("uploader =", value, "uploader");
            return (Criteria) this;
        }

        public Criteria andUploaderNotEqualTo(Integer value) {
            addCriterion("uploader <>", value, "uploader");
            return (Criteria) this;
        }

        public Criteria andUploaderGreaterThan(Integer value) {
            addCriterion("uploader >", value, "uploader");
            return (Criteria) this;
        }

        public Criteria andUploaderGreaterThanOrEqualTo(Integer value) {
            addCriterion("uploader >=", value, "uploader");
            return (Criteria) this;
        }

        public Criteria andUploaderLessThan(Integer value) {
            addCriterion("uploader <", value, "uploader");
            return (Criteria) this;
        }

        public Criteria andUploaderLessThanOrEqualTo(Integer value) {
            addCriterion("uploader <=", value, "uploader");
            return (Criteria) this;
        }

        public Criteria andUploaderIn(List<Integer> values) {
            addCriterion("uploader in", values, "uploader");
            return (Criteria) this;
        }

        public Criteria andUploaderNotIn(List<Integer> values) {
            addCriterion("uploader not in", values, "uploader");
            return (Criteria) this;
        }

        public Criteria andUploaderBetween(Integer value1, Integer value2) {
            addCriterion("uploader between", value1, value2, "uploader");
            return (Criteria) this;
        }

        public Criteria andUploaderNotBetween(Integer value1, Integer value2) {
            addCriterion("uploader not between", value1, value2, "uploader");
            return (Criteria) this;
        }

        public Criteria andDateIsNull() {
            addCriterion("date is null");
            return (Criteria) this;
        }

        public Criteria andDateIsNotNull() {
            addCriterion("date is not null");
            return (Criteria) this;
        }

        public Criteria andDateEqualTo(Date value) {
            addCriterionForJDBCDate("date =", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("date <>", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateGreaterThan(Date value) {
            addCriterionForJDBCDate("date >", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("date >=", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLessThan(Date value) {
            addCriterionForJDBCDate("date <", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("date <=", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateIn(List<Date> values) {
            addCriterionForJDBCDate("date in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("date not in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("date between", value1, value2, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("date not between", value1, value2, "date");
            return (Criteria) this;
        }

        public Criteria andSourceIsNull() {
            addCriterion("source is null");
            return (Criteria) this;
        }

        public Criteria andSourceIsNotNull() {
            addCriterion("source is not null");
            return (Criteria) this;
        }

        public Criteria andSourceEqualTo(String value) {
            addCriterion("source =", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotEqualTo(String value) {
            addCriterion("source <>", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThan(String value) {
            addCriterion("source >", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThanOrEqualTo(String value) {
            addCriterion("source >=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThan(String value) {
            addCriterion("source <", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThanOrEqualTo(String value) {
            addCriterion("source <=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLike(String value) {
            addCriterion("source like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotLike(String value) {
            addCriterion("source not like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceIn(List<String> values) {
            addCriterion("source in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotIn(List<String> values) {
            addCriterion("source not in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceBetween(String value1, String value2) {
            addCriterion("source between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotBetween(String value1, String value2) {
            addCriterion("source not between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andOriginalFormatIsNull() {
            addCriterion("original_format is null");
            return (Criteria) this;
        }

        public Criteria andOriginalFormatIsNotNull() {
            addCriterion("original_format is not null");
            return (Criteria) this;
        }

        public Criteria andOriginalFormatEqualTo(String value) {
            addCriterion("original_format =", value, "originalFormat");
            return (Criteria) this;
        }

        public Criteria andOriginalFormatNotEqualTo(String value) {
            addCriterion("original_format <>", value, "originalFormat");
            return (Criteria) this;
        }

        public Criteria andOriginalFormatGreaterThan(String value) {
            addCriterion("original_format >", value, "originalFormat");
            return (Criteria) this;
        }

        public Criteria andOriginalFormatGreaterThanOrEqualTo(String value) {
            addCriterion("original_format >=", value, "originalFormat");
            return (Criteria) this;
        }

        public Criteria andOriginalFormatLessThan(String value) {
            addCriterion("original_format <", value, "originalFormat");
            return (Criteria) this;
        }

        public Criteria andOriginalFormatLessThanOrEqualTo(String value) {
            addCriterion("original_format <=", value, "originalFormat");
            return (Criteria) this;
        }

        public Criteria andOriginalFormatLike(String value) {
            addCriterion("original_format like", value, "originalFormat");
            return (Criteria) this;
        }

        public Criteria andOriginalFormatNotLike(String value) {
            addCriterion("original_format not like", value, "originalFormat");
            return (Criteria) this;
        }

        public Criteria andOriginalFormatIn(List<String> values) {
            addCriterion("original_format in", values, "originalFormat");
            return (Criteria) this;
        }

        public Criteria andOriginalFormatNotIn(List<String> values) {
            addCriterion("original_format not in", values, "originalFormat");
            return (Criteria) this;
        }

        public Criteria andOriginalFormatBetween(String value1, String value2) {
            addCriterion("original_format between", value1, value2, "originalFormat");
            return (Criteria) this;
        }

        public Criteria andOriginalFormatNotBetween(String value1, String value2) {
            addCriterion("original_format not between", value1, value2, "originalFormat");
            return (Criteria) this;
        }

        public Criteria andFormatChangedIsNull() {
            addCriterion("format_changed is null");
            return (Criteria) this;
        }

        public Criteria andFormatChangedIsNotNull() {
            addCriterion("format_changed is not null");
            return (Criteria) this;
        }

        public Criteria andFormatChangedEqualTo(Boolean value) {
            addCriterion("format_changed =", value, "formatChanged");
            return (Criteria) this;
        }

        public Criteria andFormatChangedNotEqualTo(Boolean value) {
            addCriterion("format_changed <>", value, "formatChanged");
            return (Criteria) this;
        }

        public Criteria andFormatChangedGreaterThan(Boolean value) {
            addCriterion("format_changed >", value, "formatChanged");
            return (Criteria) this;
        }

        public Criteria andFormatChangedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("format_changed >=", value, "formatChanged");
            return (Criteria) this;
        }

        public Criteria andFormatChangedLessThan(Boolean value) {
            addCriterion("format_changed <", value, "formatChanged");
            return (Criteria) this;
        }

        public Criteria andFormatChangedLessThanOrEqualTo(Boolean value) {
            addCriterion("format_changed <=", value, "formatChanged");
            return (Criteria) this;
        }

        public Criteria andFormatChangedIn(List<Boolean> values) {
            addCriterion("format_changed in", values, "formatChanged");
            return (Criteria) this;
        }

        public Criteria andFormatChangedNotIn(List<Boolean> values) {
            addCriterion("format_changed not in", values, "formatChanged");
            return (Criteria) this;
        }

        public Criteria andFormatChangedBetween(Boolean value1, Boolean value2) {
            addCriterion("format_changed between", value1, value2, "formatChanged");
            return (Criteria) this;
        }

        public Criteria andFormatChangedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("format_changed not between", value1, value2, "formatChanged");
            return (Criteria) this;
        }

        public Criteria andTxtPathIsNull() {
            addCriterion("txt_path is null");
            return (Criteria) this;
        }

        public Criteria andTxtPathIsNotNull() {
            addCriterion("txt_path is not null");
            return (Criteria) this;
        }

        public Criteria andTxtPathEqualTo(String value) {
            addCriterion("txt_path =", value, "txtPath");
            return (Criteria) this;
        }

        public Criteria andTxtPathNotEqualTo(String value) {
            addCriterion("txt_path <>", value, "txtPath");
            return (Criteria) this;
        }

        public Criteria andTxtPathGreaterThan(String value) {
            addCriterion("txt_path >", value, "txtPath");
            return (Criteria) this;
        }

        public Criteria andTxtPathGreaterThanOrEqualTo(String value) {
            addCriterion("txt_path >=", value, "txtPath");
            return (Criteria) this;
        }

        public Criteria andTxtPathLessThan(String value) {
            addCriterion("txt_path <", value, "txtPath");
            return (Criteria) this;
        }

        public Criteria andTxtPathLessThanOrEqualTo(String value) {
            addCriterion("txt_path <=", value, "txtPath");
            return (Criteria) this;
        }

        public Criteria andTxtPathLike(String value) {
            addCriterion("txt_path like", value, "txtPath");
            return (Criteria) this;
        }

        public Criteria andTxtPathNotLike(String value) {
            addCriterion("txt_path not like", value, "txtPath");
            return (Criteria) this;
        }

        public Criteria andTxtPathIn(List<String> values) {
            addCriterion("txt_path in", values, "txtPath");
            return (Criteria) this;
        }

        public Criteria andTxtPathNotIn(List<String> values) {
            addCriterion("txt_path not in", values, "txtPath");
            return (Criteria) this;
        }

        public Criteria andTxtPathBetween(String value1, String value2) {
            addCriterion("txt_path between", value1, value2, "txtPath");
            return (Criteria) this;
        }

        public Criteria andTxtPathNotBetween(String value1, String value2) {
            addCriterion("txt_path not between", value1, value2, "txtPath");
            return (Criteria) this;
        }

        public Criteria andCleanedIsNull() {
            addCriterion("cleaned is null");
            return (Criteria) this;
        }

        public Criteria andCleanedIsNotNull() {
            addCriterion("cleaned is not null");
            return (Criteria) this;
        }

        public Criteria andCleanedEqualTo(Boolean value) {
            addCriterion("cleaned =", value, "cleaned");
            return (Criteria) this;
        }

        public Criteria andCleanedNotEqualTo(Boolean value) {
            addCriterion("cleaned <>", value, "cleaned");
            return (Criteria) this;
        }

        public Criteria andCleanedGreaterThan(Boolean value) {
            addCriterion("cleaned >", value, "cleaned");
            return (Criteria) this;
        }

        public Criteria andCleanedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("cleaned >=", value, "cleaned");
            return (Criteria) this;
        }

        public Criteria andCleanedLessThan(Boolean value) {
            addCriterion("cleaned <", value, "cleaned");
            return (Criteria) this;
        }

        public Criteria andCleanedLessThanOrEqualTo(Boolean value) {
            addCriterion("cleaned <=", value, "cleaned");
            return (Criteria) this;
        }

        public Criteria andCleanedIn(List<Boolean> values) {
            addCriterion("cleaned in", values, "cleaned");
            return (Criteria) this;
        }

        public Criteria andCleanedNotIn(List<Boolean> values) {
            addCriterion("cleaned not in", values, "cleaned");
            return (Criteria) this;
        }

        public Criteria andCleanedBetween(Boolean value1, Boolean value2) {
            addCriterion("cleaned between", value1, value2, "cleaned");
            return (Criteria) this;
        }

        public Criteria andCleanedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("cleaned not between", value1, value2, "cleaned");
            return (Criteria) this;
        }

        public Criteria andCleanedPathIsNull() {
            addCriterion("cleaned_path is null");
            return (Criteria) this;
        }

        public Criteria andCleanedPathIsNotNull() {
            addCriterion("cleaned_path is not null");
            return (Criteria) this;
        }

        public Criteria andCleanedPathEqualTo(String value) {
            addCriterion("cleaned_path =", value, "cleanedPath");
            return (Criteria) this;
        }

        public Criteria andCleanedPathNotEqualTo(String value) {
            addCriterion("cleaned_path <>", value, "cleanedPath");
            return (Criteria) this;
        }

        public Criteria andCleanedPathGreaterThan(String value) {
            addCriterion("cleaned_path >", value, "cleanedPath");
            return (Criteria) this;
        }

        public Criteria andCleanedPathGreaterThanOrEqualTo(String value) {
            addCriterion("cleaned_path >=", value, "cleanedPath");
            return (Criteria) this;
        }

        public Criteria andCleanedPathLessThan(String value) {
            addCriterion("cleaned_path <", value, "cleanedPath");
            return (Criteria) this;
        }

        public Criteria andCleanedPathLessThanOrEqualTo(String value) {
            addCriterion("cleaned_path <=", value, "cleanedPath");
            return (Criteria) this;
        }

        public Criteria andCleanedPathLike(String value) {
            addCriterion("cleaned_path like", value, "cleanedPath");
            return (Criteria) this;
        }

        public Criteria andCleanedPathNotLike(String value) {
            addCriterion("cleaned_path not like", value, "cleanedPath");
            return (Criteria) this;
        }

        public Criteria andCleanedPathIn(List<String> values) {
            addCriterion("cleaned_path in", values, "cleanedPath");
            return (Criteria) this;
        }

        public Criteria andCleanedPathNotIn(List<String> values) {
            addCriterion("cleaned_path not in", values, "cleanedPath");
            return (Criteria) this;
        }

        public Criteria andCleanedPathBetween(String value1, String value2) {
            addCriterion("cleaned_path between", value1, value2, "cleanedPath");
            return (Criteria) this;
        }

        public Criteria andCleanedPathNotBetween(String value1, String value2) {
            addCriterion("cleaned_path not between", value1, value2, "cleanedPath");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table original
     *
     * @mbg.generated do_not_delete_during_merge Sat Dec 07 09:30:00 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table original
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}