package com.wcq.thang.model;

import java.util.ArrayList;
import java.util.List;

public class TcorpusExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tcorpus
     *
     * @mbg.generated Sun Dec 15 14:39:47 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tcorpus
     *
     * @mbg.generated Sun Dec 15 14:39:47 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tcorpus
     *
     * @mbg.generated Sun Dec 15 14:39:47 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcorpus
     *
     * @mbg.generated Sun Dec 15 14:39:47 CST 2019
     */
    public TcorpusExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcorpus
     *
     * @mbg.generated Sun Dec 15 14:39:47 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcorpus
     *
     * @mbg.generated Sun Dec 15 14:39:47 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcorpus
     *
     * @mbg.generated Sun Dec 15 14:39:47 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcorpus
     *
     * @mbg.generated Sun Dec 15 14:39:47 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcorpus
     *
     * @mbg.generated Sun Dec 15 14:39:47 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcorpus
     *
     * @mbg.generated Sun Dec 15 14:39:47 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcorpus
     *
     * @mbg.generated Sun Dec 15 14:39:47 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcorpus
     *
     * @mbg.generated Sun Dec 15 14:39:47 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcorpus
     *
     * @mbg.generated Sun Dec 15 14:39:47 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcorpus
     *
     * @mbg.generated Sun Dec 15 14:39:47 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tcorpus
     *
     * @mbg.generated Sun Dec 15 14:39:47 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCorpusIdIsNull() {
            addCriterion("corpus_id is null");
            return (Criteria) this;
        }

        public Criteria andCorpusIdIsNotNull() {
            addCriterion("corpus_id is not null");
            return (Criteria) this;
        }

        public Criteria andCorpusIdEqualTo(Integer value) {
            addCriterion("corpus_id =", value, "corpusId");
            return (Criteria) this;
        }

        public Criteria andCorpusIdNotEqualTo(Integer value) {
            addCriterion("corpus_id <>", value, "corpusId");
            return (Criteria) this;
        }

        public Criteria andCorpusIdGreaterThan(Integer value) {
            addCriterion("corpus_id >", value, "corpusId");
            return (Criteria) this;
        }

        public Criteria andCorpusIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("corpus_id >=", value, "corpusId");
            return (Criteria) this;
        }

        public Criteria andCorpusIdLessThan(Integer value) {
            addCriterion("corpus_id <", value, "corpusId");
            return (Criteria) this;
        }

        public Criteria andCorpusIdLessThanOrEqualTo(Integer value) {
            addCriterion("corpus_id <=", value, "corpusId");
            return (Criteria) this;
        }

        public Criteria andCorpusIdIn(List<Integer> values) {
            addCriterion("corpus_id in", values, "corpusId");
            return (Criteria) this;
        }

        public Criteria andCorpusIdNotIn(List<Integer> values) {
            addCriterion("corpus_id not in", values, "corpusId");
            return (Criteria) this;
        }

        public Criteria andCorpusIdBetween(Integer value1, Integer value2) {
            addCriterion("corpus_id between", value1, value2, "corpusId");
            return (Criteria) this;
        }

        public Criteria andCorpusIdNotBetween(Integer value1, Integer value2) {
            addCriterion("corpus_id not between", value1, value2, "corpusId");
            return (Criteria) this;
        }

        public Criteria andOriginalIdIsNull() {
            addCriterion("original_id is null");
            return (Criteria) this;
        }

        public Criteria andOriginalIdIsNotNull() {
            addCriterion("original_id is not null");
            return (Criteria) this;
        }

        public Criteria andOriginalIdEqualTo(Integer value) {
            addCriterion("original_id =", value, "originalId");
            return (Criteria) this;
        }

        public Criteria andOriginalIdNotEqualTo(Integer value) {
            addCriterion("original_id <>", value, "originalId");
            return (Criteria) this;
        }

        public Criteria andOriginalIdGreaterThan(Integer value) {
            addCriterion("original_id >", value, "originalId");
            return (Criteria) this;
        }

        public Criteria andOriginalIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("original_id >=", value, "originalId");
            return (Criteria) this;
        }

        public Criteria andOriginalIdLessThan(Integer value) {
            addCriterion("original_id <", value, "originalId");
            return (Criteria) this;
        }

        public Criteria andOriginalIdLessThanOrEqualTo(Integer value) {
            addCriterion("original_id <=", value, "originalId");
            return (Criteria) this;
        }

        public Criteria andOriginalIdIn(List<Integer> values) {
            addCriterion("original_id in", values, "originalId");
            return (Criteria) this;
        }

        public Criteria andOriginalIdNotIn(List<Integer> values) {
            addCriterion("original_id not in", values, "originalId");
            return (Criteria) this;
        }

        public Criteria andOriginalIdBetween(Integer value1, Integer value2) {
            addCriterion("original_id between", value1, value2, "originalId");
            return (Criteria) this;
        }

        public Criteria andOriginalIdNotBetween(Integer value1, Integer value2) {
            addCriterion("original_id not between", value1, value2, "originalId");
            return (Criteria) this;
        }

        public Criteria andStandardContentIsNull() {
            addCriterion("standard_content is null");
            return (Criteria) this;
        }

        public Criteria andStandardContentIsNotNull() {
            addCriterion("standard_content is not null");
            return (Criteria) this;
        }

        public Criteria andStandardContentEqualTo(String value) {
            addCriterion("standard_content =", value, "standardContent");
            return (Criteria) this;
        }

        public Criteria andStandardContentNotEqualTo(String value) {
            addCriterion("standard_content <>", value, "standardContent");
            return (Criteria) this;
        }

        public Criteria andStandardContentGreaterThan(String value) {
            addCriterion("standard_content >", value, "standardContent");
            return (Criteria) this;
        }

        public Criteria andStandardContentGreaterThanOrEqualTo(String value) {
            addCriterion("standard_content >=", value, "standardContent");
            return (Criteria) this;
        }

        public Criteria andStandardContentLessThan(String value) {
            addCriterion("standard_content <", value, "standardContent");
            return (Criteria) this;
        }

        public Criteria andStandardContentLessThanOrEqualTo(String value) {
            addCriterion("standard_content <=", value, "standardContent");
            return (Criteria) this;
        }

        public Criteria andStandardContentLike(String value) {
            addCriterion("standard_content like", value, "standardContent");
            return (Criteria) this;
        }

        public Criteria andStandardContentNotLike(String value) {
            addCriterion("standard_content not like", value, "standardContent");
            return (Criteria) this;
        }

        public Criteria andStandardContentIn(List<String> values) {
            addCriterion("standard_content in", values, "standardContent");
            return (Criteria) this;
        }

        public Criteria andStandardContentNotIn(List<String> values) {
            addCriterion("standard_content not in", values, "standardContent");
            return (Criteria) this;
        }

        public Criteria andStandardContentBetween(String value1, String value2) {
            addCriterion("standard_content between", value1, value2, "standardContent");
            return (Criteria) this;
        }

        public Criteria andStandardContentNotBetween(String value1, String value2) {
            addCriterion("standard_content not between", value1, value2, "standardContent");
            return (Criteria) this;
        }

        public Criteria andCixingContentIsNull() {
            addCriterion("cixing_content is null");
            return (Criteria) this;
        }

        public Criteria andCixingContentIsNotNull() {
            addCriterion("cixing_content is not null");
            return (Criteria) this;
        }

        public Criteria andCixingContentEqualTo(String value) {
            addCriterion("cixing_content =", value, "cixingContent");
            return (Criteria) this;
        }

        public Criteria andCixingContentNotEqualTo(String value) {
            addCriterion("cixing_content <>", value, "cixingContent");
            return (Criteria) this;
        }

        public Criteria andCixingContentGreaterThan(String value) {
            addCriterion("cixing_content >", value, "cixingContent");
            return (Criteria) this;
        }

        public Criteria andCixingContentGreaterThanOrEqualTo(String value) {
            addCriterion("cixing_content >=", value, "cixingContent");
            return (Criteria) this;
        }

        public Criteria andCixingContentLessThan(String value) {
            addCriterion("cixing_content <", value, "cixingContent");
            return (Criteria) this;
        }

        public Criteria andCixingContentLessThanOrEqualTo(String value) {
            addCriterion("cixing_content <=", value, "cixingContent");
            return (Criteria) this;
        }

        public Criteria andCixingContentLike(String value) {
            addCriterion("cixing_content like", value, "cixingContent");
            return (Criteria) this;
        }

        public Criteria andCixingContentNotLike(String value) {
            addCriterion("cixing_content not like", value, "cixingContent");
            return (Criteria) this;
        }

        public Criteria andCixingContentIn(List<String> values) {
            addCriterion("cixing_content in", values, "cixingContent");
            return (Criteria) this;
        }

        public Criteria andCixingContentNotIn(List<String> values) {
            addCriterion("cixing_content not in", values, "cixingContent");
            return (Criteria) this;
        }

        public Criteria andCixingContentBetween(String value1, String value2) {
            addCriterion("cixing_content between", value1, value2, "cixingContent");
            return (Criteria) this;
        }

        public Criteria andCixingContentNotBetween(String value1, String value2) {
            addCriterion("cixing_content not between", value1, value2, "cixingContent");
            return (Criteria) this;
        }

        public Criteria andInlinesIsNull() {
            addCriterion("inlines is null");
            return (Criteria) this;
        }

        public Criteria andInlinesIsNotNull() {
            addCriterion("inlines is not null");
            return (Criteria) this;
        }

        public Criteria andInlinesEqualTo(Integer value) {
            addCriterion("inlines =", value, "inlines");
            return (Criteria) this;
        }

        public Criteria andInlinesNotEqualTo(Integer value) {
            addCriterion("inlines <>", value, "inlines");
            return (Criteria) this;
        }

        public Criteria andInlinesGreaterThan(Integer value) {
            addCriterion("inlines >", value, "inlines");
            return (Criteria) this;
        }

        public Criteria andInlinesGreaterThanOrEqualTo(Integer value) {
            addCriterion("inlines >=", value, "inlines");
            return (Criteria) this;
        }

        public Criteria andInlinesLessThan(Integer value) {
            addCriterion("inlines <", value, "inlines");
            return (Criteria) this;
        }

        public Criteria andInlinesLessThanOrEqualTo(Integer value) {
            addCriterion("inlines <=", value, "inlines");
            return (Criteria) this;
        }

        public Criteria andInlinesIn(List<Integer> values) {
            addCriterion("inlines in", values, "inlines");
            return (Criteria) this;
        }

        public Criteria andInlinesNotIn(List<Integer> values) {
            addCriterion("inlines not in", values, "inlines");
            return (Criteria) this;
        }

        public Criteria andInlinesBetween(Integer value1, Integer value2) {
            addCriterion("inlines between", value1, value2, "inlines");
            return (Criteria) this;
        }

        public Criteria andInlinesNotBetween(Integer value1, Integer value2) {
            addCriterion("inlines not between", value1, value2, "inlines");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tcorpus
     *
     * @mbg.generated do_not_delete_during_merge Sun Dec 15 14:39:47 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tcorpus
     *
     * @mbg.generated Sun Dec 15 14:39:47 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}