package com.wcq.thang.model;

public class Tcorpus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcorpus.corpus_id
     *
     * @mbg.generated Sun Dec 15 14:39:47 CST 2019
     */
    private Integer corpusId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcorpus.original_id
     *
     * @mbg.generated Sun Dec 15 14:39:47 CST 2019
     */
    private Integer originalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcorpus.standard_content
     *
     * @mbg.generated Sun Dec 15 14:39:47 CST 2019
     */
    private String standardContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcorpus.cixing_content
     *
     * @mbg.generated Sun Dec 15 14:39:47 CST 2019
     */
    private String cixingContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcorpus.inlines
     *
     * @mbg.generated Sun Dec 15 14:39:47 CST 2019
     */
    private Integer inlines;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcorpus.corpus_id
     *
     * @return the value of tcorpus.corpus_id
     *
     * @mbg.generated Sun Dec 15 14:39:47 CST 2019
     */
    public Integer getCorpusId() {
        return corpusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcorpus.corpus_id
     *
     * @param corpusId the value for tcorpus.corpus_id
     *
     * @mbg.generated Sun Dec 15 14:39:47 CST 2019
     */
    public void setCorpusId(Integer corpusId) {
        this.corpusId = corpusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcorpus.original_id
     *
     * @return the value of tcorpus.original_id
     *
     * @mbg.generated Sun Dec 15 14:39:47 CST 2019
     */
    public Integer getOriginalId() {
        return originalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcorpus.original_id
     *
     * @param originalId the value for tcorpus.original_id
     *
     * @mbg.generated Sun Dec 15 14:39:47 CST 2019
     */
    public void setOriginalId(Integer originalId) {
        this.originalId = originalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcorpus.standard_content
     *
     * @return the value of tcorpus.standard_content
     *
     * @mbg.generated Sun Dec 15 14:39:47 CST 2019
     */
    public String getStandardContent() {
        return standardContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcorpus.standard_content
     *
     * @param standardContent the value for tcorpus.standard_content
     *
     * @mbg.generated Sun Dec 15 14:39:47 CST 2019
     */
    public void setStandardContent(String standardContent) {
        this.standardContent = standardContent == null ? null : standardContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcorpus.cixing_content
     *
     * @return the value of tcorpus.cixing_content
     *
     * @mbg.generated Sun Dec 15 14:39:47 CST 2019
     */
    public String getCixingContent() {
        return cixingContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcorpus.cixing_content
     *
     * @param cixingContent the value for tcorpus.cixing_content
     *
     * @mbg.generated Sun Dec 15 14:39:47 CST 2019
     */
    public void setCixingContent(String cixingContent) {
        this.cixingContent = cixingContent == null ? null : cixingContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcorpus.inlines
     *
     * @return the value of tcorpus.inlines
     *
     * @mbg.generated Sun Dec 15 14:39:47 CST 2019
     */
    public Integer getInlines() {
        return inlines;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcorpus.inlines
     *
     * @param inlines the value for tcorpus.inlines
     *
     * @mbg.generated Sun Dec 15 14:39:47 CST 2019
     */
    public void setInlines(Integer inlines) {
        this.inlines = inlines;
    }
}