package com.wcq.thang.mapper;

import com.wcq.thang.model.Mature;
import com.wcq.thang.model.MatureExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MatureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mature
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    long countByExample(MatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mature
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    int deleteByExample(MatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mature
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    int deleteByPrimaryKey(Integer matureId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mature
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    int insert(Mature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mature
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    int insertSelective(Mature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mature
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    List<Mature> selectByExample(MatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mature
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    Mature selectByPrimaryKey(Integer matureId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mature
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    int updateByExampleSelective(@Param("record") Mature record, @Param("example") MatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mature
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    int updateByExample(@Param("record") Mature record, @Param("example") MatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mature
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    int updateByPrimaryKeySelective(Mature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mature
     *
     * @mbg.generated Sat Dec 07 09:30:00 CST 2019
     */
    int updateByPrimaryKey(Mature record);
}