package com.wcq.thang.mapper;

import com.wcq.thang.model.Tcorpus;
import com.wcq.thang.model.TcorpusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TcorpusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcorpus
     *
     * @mbg.generated Sun Dec 15 14:39:47 CST 2019
     */
    long countByExample(TcorpusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcorpus
     *
     * @mbg.generated Sun Dec 15 14:39:47 CST 2019
     */
    int deleteByExample(TcorpusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcorpus
     *
     * @mbg.generated Sun Dec 15 14:39:47 CST 2019
     */
    int deleteByPrimaryKey(Integer corpusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcorpus
     *
     * @mbg.generated Sun Dec 15 14:39:47 CST 2019
     */
    int insert(Tcorpus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcorpus
     *
     * @mbg.generated Sun Dec 15 14:39:47 CST 2019
     */
    int insertSelective(Tcorpus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcorpus
     *
     * @mbg.generated Sun Dec 15 14:39:47 CST 2019
     */
    List<Tcorpus> selectByExample(TcorpusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcorpus
     *
     * @mbg.generated Sun Dec 15 14:39:47 CST 2019
     */
    Tcorpus selectByPrimaryKey(Integer corpusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcorpus
     *
     * @mbg.generated Sun Dec 15 14:39:47 CST 2019
     */
    int updateByExampleSelective(@Param("record") Tcorpus record, @Param("example") TcorpusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcorpus
     *
     * @mbg.generated Sun Dec 15 14:39:47 CST 2019
     */
    int updateByExample(@Param("record") Tcorpus record, @Param("example") TcorpusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcorpus
     *
     * @mbg.generated Sun Dec 15 14:39:47 CST 2019
     */
    int updateByPrimaryKeySelective(Tcorpus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcorpus
     *
     * @mbg.generated Sun Dec 15 14:39:47 CST 2019
     */
    int updateByPrimaryKey(Tcorpus record);
}